version: '3'

services:
  web:
    container_name: guide-web
    build:
      context: .
      dockerfile: ./etc/docker/web/Dockerfile
      args:
        APP_ENV: $APP_ENV
    ports:
      - 9780:80
    volumes:
      - .:/var/www/html

